blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/svrooij/sonos-api-docs/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: All discussions
    url: https://github.com/svrooij/sonos-api-docs/discussions
    about: General discussions about the Sonos API.